language: android
android:
  components:
    # The BuildTools version used by your project
    - build-tools-25.0.1
    # The SDK version used to compile your project
    - android-21
  before_script:
    - gradle -v 
